<MyFloat>:
    Image:
        source:''

    Button:
        id: image_save_button
        icon:'translate'
        text:'Translate'
        # size_hint: .20,.20
        # pos_hint: {'left':.25,'top':.1}
        # on_press: root.take_picture()

    Button:
        id: image_back_button
        icon:'translate'
        text:'Back'
        pos_hint: {'right':.25,'top':.1}
        on_press: root.take_picture()


            

